#!/bin/sh
# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2013.3
# Copyright (C) 2013 Xilinx Inc. All rights reserved.
# 
# ==============================================================

rm -rf csrc simv* *.log work *.vpd *.key WORK

mkdir -p work
for f in *.v
do
vlogan -full64 +v2k -nc -work work "$f" -xzcheck -ignore all
done

vcs apatb_dct_top -l comp.log +lint=PCWM -debug_pp -full64 -ignore all

