#!/bin/sh
# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2013.3
# Copyright (C) 2013 Xilinx Inc. All rights reserved.
# 
# ==============================================================


./simv +vcs+nostdout -ucli -do dump_waveform.cmds
vcd2saif -64 -input matrixmul_trace.vpd -output activity.saif


