#!/bin/sh
# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2013.3
# Copyright (C) 2013 Xilinx Inc. All rights reserved.
# 
# ==============================================================

# The next line restarts using autoesl tclsh \
    exec vivado_hls run_sim.tcl
