#!/bin/sh
# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2013.3
# Copyright (C) 2013 Xilinx Inc. All rights reserved.
# 
# ==============================================================

rm -rf csrc simv* *.log work *.vpd *.key WORK

mkdir -p work


vlogan -full64 +v2k -C -work work "../verilog/AESL_automem_indata.v" 
vlogan -full64 +v2k -C -work work "../verilog/AESL_automem_outdata.v"  
vlogan -full64 +v2k -C -work work "../verilog/AESL_automem_tmp.v"  
vlogan -full64 +v2k -C -work work "dct.autotb.v"  
vlogan -full64 +v2k -C -work work "../synth/gate/dct-final.v"  +zero_delay_mode
vlogan -full64 +v2k -C -work work "/home/polaris/dlee/.local/synopsys_db/NangateOpenCellLibrary.v"  +delay_mode_zero +notimingcheck

vcs apatb_dct_top -debug 

